# Generated by Django 4.0.3 on 2022-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.ImageField(blank=True, default='room_icon.png', null=True, upload_to=''),
        ),
    ]
