# Generated by Django 4.0.3 on 2022-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_room_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.ImageField(blank=True, default='room.png', null=True, upload_to=''),
        ),
    ]
