# Generated by Django 4.0.3 on 2022-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
