# Generated by Django 4.0.3 on 2022-03-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_topic_name_topic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
